name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build with Webpack
        run: npm run build:umd

      - name: Get file names
        id: getFiles
        run: echo "::set-output name=files::$(ls dist)"

      - name: Upload files to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*
          asset_name: ${{ matrix.filename }}
          asset_content_type: application/javascript
        env:
          FILES: ${{ steps.getFiles.outputs.files }}
