name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with Webpack
        run: npm run build:umd

      - name: Save output variable to file
        id: getFiles
        run: echo "dist/*.js" >> $GITHUB_ENV

      - name: Upload JavaScript files to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.js
          asset_name: ${{ env.FILES }}
          asset_content_type: application/javascript

      - name: Upload Source Map file to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.js.map
          asset_name: ${{ env.FILES }}.map
          asset_content_type: application/octet-stream
